import Header from "./common/header";
import Footer from "./common/footer";
import HomeBanner from "./homeBanner";
import Services from "./services";
import Sponser from "./sponser";
import Courses from "./courses";
import MoreServices from "./moreServices";
import Job from "./job";
import Testimonial from "./testimonial";
export { Header, Footer, HomeBanner, Services, Sponser, Courses, MoreServices, Job, Testimonial };
